apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-server-deployment
spec:
  selector:
    matchLabels:
      app: af-server
  replicas: 1
  template:
    metadata:
      labels:
        app: af-server
        env: development
    spec:
      containers:
      - name: af-server
        image: gcr.io/avian-safeguard-192506/af-server:v2
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: af-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: af-server